# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

global: &global
  rollbar_server_token: ''
  mandrill_user_name: ''
  mandrill_api_token: ''
  facebook_key: '149901595679464'
  facebook_secret: '57144fcb786054061b3d5f8d733dc991'
  sms_userid: qtracc
  sms_passwd: bm345
  sms_url: http://onlysms.ae/api/api_http.php
  sms_senderid: 'SMS%20ALERT'

development:
  <<: *global
  secret_key_base: 2f25635d8509c06197df6cda6612c4b52497751921f1583b2f27500ecd8bdc18810af2bfef10720364bc24236fe6af0c299f9d6645112f3d146f95927d82cfce

test:
  <<: *global
  secret_key_base: 812681c87b0d07b3299e8a604f8eab20c18b285f9694e8a957cb78a87b7a06d03e329b7cf921c0e6c16a3c6f3d587dc8dcf1e59457423799c31917948660eafa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  <<: *global
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
